name: Deploy to Production

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Deploy
        run: |
          echo "🚀 Deploy step - Integrating with EasyPanel"

          if [ -n "${{ secrets.WEBHOOK_URL }}" ]; then
            curl "${{ secrets.WEBHOOK_URL }}"
          fi
